# Generated by Django 3.2.16 on 2022-12-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_captcha_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='share_2',
            field=models.BinaryField(null=True),
        ),
    ]
