# Generated by Django 3.2.16 on 2022-12-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_captcha_share_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.controlvote'),
        ),
    ]
