# Generated by Django 3.2.16 on 2022-12-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_captcha_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='voter',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
