# Generated by Django 3.2.16 on 2023-01-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_rename_share_2_captcha_share_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captcha',
            old_name='share_1',
            new_name='share_2',
        ),
    ]
